Feature/add prettierrc.json
SomosCodear/codear-site pull request #193
Opened 2020-11-04 13:00 UTC by alexrobaina

Hola! Pensé que estaría bueno utilizar prettier para estandarizar el formato del código al guardar.
- Integré prettier
- Actualicé husky
- Lo probé en 2 archivos 
- Agregue al .gitignore el archivo yarn.lock

2020-11-04 18:07 UTC, homer0 requested changes
Definitivamente es algo super útil y que deberíamos implementar, así que desde ya, muchas gracias!!

Disculpa que te deje varios comments, pero son más que nada para charlar que "NO"s :P.

2020-11-05 01:30 UTC, asermax commented on .prettierrc.json
> +  "singleQuote": true,
Agree con las dos cosas que planteas 👌

2020-11-05 01:38 UTC, asermax commented
Tbh no soy muy fan de prettier por que eslint me parece bastante más útil y tener que mantener dos configs en sync y que pueden tener conflictos me da mucha vagancia.
Dicho eso, no estoy en contra de meterlo pero no tengo mucho para comentar, asi que lo dejo a disposición de homer0 :P

2020-11-05 02:11 UTC, alexrobaina commented on .gitignore
> +yarn.lock
Vale! Voy a leer más al respecto, no sabia qué yarn.lock tenia esa responsabilidad! En un momento tuve problemas con yarn.lock y me recomendaron sacarlo del repo. Nunca pude entender porque me rompía en producción. 

Gracias por la explicación 😄   

jeje contradictorio que esté yarn.lock en .gitignore y este pusheado, sorry por el descuido. 😄

2020-11-05 02:25 UTC, alexrobaina commented on .prettierrc.json
> +    },
🤔 entiendo, entonces esto estaría de más, las puedo sacar para que tome la configuración que esta en el Top level. 😄

2020-11-05 11:54 UTC, alexrobaina commented
Hola @homer0 muchas gracias por los comentarios, estoy super abierto a ellos ya que de esa forma puedo seguir aprendiendo.

Ayer me puse a leer un poco la documentación de prettier y efectivamente la configuración de scss y css no funciona por sí sola hay que agregar otras cositas pero más haya de eso no tiene sentido que lo agreguemos acá porque no archivos de scss y el de css es mini. 

También hice como 5 commit  al pedo porque estaba intentando configurar un pre-commit pero al final no pude 😞 

@asermax entiendo lo que dices sobre el mantenimiento de dos configs, el problema que veo de no tener el prettier es que cada vez que tocaba un archivo se formateaba re diferente a como lo tenia ustedes y me pareció buena idea sumarlo. 😄

Hice un commit con los cambios y recomendaciones que plantea Homero.
Cualquier cosa me avisan 😄

2020-11-05 19:21 UTC, homer0 commented
@alexrobaina Genial el research y los cambios que hiciste :D; un par de cositas más que podrías agregar, y que salieron de lo que vos y el Agus dijeron:

- Sync con ESLint: Podes instalar [`eslint-config-prettier`](http://npmjs.com/eslint-config-prettier) y en el `.eslintrc`, en el `extends`, después de `"airbnb/hooks"`, agrega `prettier`. Esa config básicamente apaga las reglas de ESLint de las que se hace cargo Prettier
- Pre commit: En el `package.json`, en la config de `lint-staged`, cambia esto:

```diff
- "*.{js,jsx}": "eslint --cache --fix"
+ "*.{js,jsx}": [""eslint --cache --fix"", "prettier --write"]
```

Probalo; si no me equivoco, eso va a correr el fix de ESLint y después va a correr Prettier, ya que la config apaga las reglas que generan conflicto, nada de lo que haga Prettier después de correr ESLint debería generar errores.


Y como un extra, `git checkout master -- ./.gitignore`, para resetear los cambios del `.gitignore` a como están en `master`.

Gracias 🤘!

2020-11-06 13:01 UTC, alexrobaina commented
Hola de nuevo 😄
Agregue los cambios que comentas y terminé borrando del pre-commit el prettier porque el mensaje que se muestra en la terminal no es muy claro. En teoría esto debería formatear cuando guardas de forma automática (? 🤔 

Adjunto imagen del mensaje de consola en el pre-commit 

![Screen Shot 2020-11-05 at 21 22 07](https://user-images.githubusercontent.com/30770802/98368766-a2f0ee00-2016-11eb-8185-53b3d1727c9c.png)

Que opinan?

Muchas gracias por las explicaciones 😄

2020-11-06 19:10 UTC, homer0 commented
@alexrobaina Hola! Ese mensaje lo viste por como lo probaste :P, me paso lo mismo ayer: Modificaste un archivo que cuando se formatea vuelve al mismo estado con el que estaba guardado, por lo que el pre-commit lo volvió a dejar como estaba comiteado antes, por lo que tu commit no tenía cambios -> `lint-staged prevented an empty git commit.`.

Si querés probarlo posta, tenés que abrirlo con un editor que no use Prettier (por las dudas estés usando vscode con el plugin), hacer un cambio que sabes que se va a formatear y poner algo extra que no existía; `lint-staged` lo va a arreglar y no vas a ver ese mensaje.

Btw, viendo el screenshot, te recomendaría que uses Node 12 o 14, las versiones impares de Node son normalmente para pruebas, nunca llegan a ser LTS.

Gracias 🤘!

2020-11-07 00:17 UTC, alexrobaina commented
@homer0 recién hice commit los cambios que comentas! Funciona genial 😄 voy a implementarlo en mis proyectos también. Disculpa por tantas idas y vueltas.
Muchas gracias por toda la data!

2020-11-07 00:19 UTC, alexrobaina commented
Casi me olvido! No sabia lo de node. Ahi me pasé a 14.12.0 😄

2020-11-07 03:01 UTC, homer0 requested changes
@alexrobaina no worries; justo he estado renegando heavy con Prettier también, así que sé que puede ser un tanto confuso :P.

Fijate que te deje un suggestion para cambiar el comando; cuando te lo mencione en ese formato, es por que eso es lo que te tiro en tu screenshot, no hace falta que vaya así :P.

Creo que para ya ir finalizando, después del fix de `lint-staged`, te diría que corras `yarn prettier --write "./src/**/*.js"` (las comillas son importantes) y hagas un commit con eso para ya tener todo el proyecto formateado.

Saludos y Gracias!

2020-11-07 16:59 UTC, alexrobaina commented
@homer0 genial! Gracias a ti! Si, simple pero no tan simple 😄
- hecho el prettier --write 👍 

Respecto a la suggestion que me dejaste si saco ``` prevented an empty git commit. ``` deja de funcionar. 
así que lo volví a agregar. En el anterior commit no me di cuenta que faltaba el . punto (Igual funcionaba 😄)
¿Te parece bien?

2020-11-09 06:39 UTC, homer0 commented
@alexrobaina lo que pasa es que `lint-staged prevented an empty git commit.` no existe :P; cuando te lo mencione, fue por que es el error que te tiraba en tu screenshot: hiciste un cambio que después de pasarlo por Prettier volvía a estar como lo que estaba commiteado, por lo que al no haber cambios, `lint-staged` previene que "se siga con un commit vacío" (sin cambios).

Acá hice una prueba con tu branch y creo que lo va a _ilustrar_ mejor :P (mil disculpas por el tamaño de la fuente, me di cuenta después de hacerlo xD):

![lintStaged](https://user-images.githubusercontent.com/6949310/98507680-d7de8a00-223c-11eb-99a0-18c65394fc74.gif)

Con ese fix ya estaríamos :D!

2020-11-09 10:36 UTC, alexrobaina commented
jajaja hora entiendo... Disculpa! Ahi hice el fix y funcionó perfecto! 
Ahí hice el commit correspondiente. 

Muchas gracias

2020-11-09 23:11 UTC, alexrobaina commented
Borré un console.log que pensé que me lo iba a reportar el eslint pero no lo hizo, supongo que esa full esta apagada.

2020-11-10 02:43 UTC, homer0 approved these changes
@alexrobaina ahh, mira vo'; ya vamos a revisar bien que reglas están prendidas, gracias por el heads up!

Te cambie el branch base a `develop`, que es el que normalmente usamos de "staging".

Muchísimas gracias por el PR y mil disculpas si te aturdí a comments!

🤘

2020-11-10 02:48 UTC, merged

2020-11-10 12:17 UTC, alexrobaina commented
@homer0 por favor, sinceramente muchas gracias por los comentarios. De esta forma se aprende un monton. 
Un abrazo, hasta el proximo PR :smile: